export const UPDATE_BURGERS_LIST = 'UPDATE_BURGERS_LIST';

export const ADD_BURGER_ITEM = 'ADD_BURGER_ITEM';

export const UPDATE_BURGER_ITEM = 'UPDATE_BURGER_ITEM';

export const REMOVE_BURGER_ITEM = 'REMOVE_BURGER_ITEM';

export const SET_BURGERS = 'SET_BURGERS';
