version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
            npm install hexo --save
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate blog
          command: hexo generate
      - persist_to_workspace:
          root: public
          paths:
            - '*'
  deploy:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - attach_workspace:
          at: public
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
            npm install hexo --save
      - add_ssh_keys:
          fingerprints:
            - 'c4:c5:34:7a:c3:39:27:23:d0:25:ab:55:0c:1c:a2:1a'
      - run:
          name: build and run
          command: |
            git config --global user.email "ivan.arabchuk@sombrainc.com"
            git config --global user.name "sombra-ivan-arabchuk"
            npm run deploy
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
