version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: preparing
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys:
          fingerprints:
            - '51:49:46:23:f3:20:98:f5:08:ae:bc:e8:b5:b5:84:39'

      - run:
          name: build and run
          command: |
            git config --global user.email "ivan.arabchuk@sombrainc.com"
            git config --global user.name "sombra-ivan-arabchuk"
            npm run deploy
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
