version: 2.1
orbs:
  docker: circleci/docker@0.5.13
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout

      - run:
          name: preparing
          command: |
            npm install

      - run:
          name: build and run
          command: |
            npm run deploy
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
