version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: preparing
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build and run
          command: |
            npm run deploy
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
