version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - attach_workspace:
          at: public
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
            npm i
            npm install hexo --save
      - add_ssh_keys:
          fingerprints:
            - '$FINGERPRINT'
      - run:
          name: build and run
          command: |
            git config --global user.email "$EMAIL"
            git config --global user.name "$USERNAME"
            export REACT_APP_NUTRITION_ID="$REACT_APP_NUTRITION_ID"
            export REACT_APP_NUTRITION_KEY="$REACT_APP_NUTRITION_KEY"
            export REACT_APP_GOOGLE_CLIENT_ID="$REACT_APP_GOOGLE_CLIENT_ID"
            npm run deploy

  test-app:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
            npm i
            npm install hexo --save
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test

workflows:
  build_and_test:
    jobs:
      - build:
          requires:
            - test-app
          filters:
            branches:
              only: master
              ignore: gh-pages
